### ISSUE TITLE
Nx 17 issue with nx-maven

### ISSUE THREAD

**Issue by jbadeau** [khalilou88/jnxplus#541]
Using Nx 17 and the nx-maven 0.12.0

I get the following error when building with with 1 parent pom and 1 lib in the nx-maven dir. Works fine on Nx 16.x

```bash
 >  NX   Failed to process project dependencies with "@jnxplus/nx-maven".

   Cannot destructure property 'projects' of 'undefined' as it is undefined.
   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

{
  stack: 'TypeError: Failed to process project dependencies with "@jnxplus/nx-maven".\n' +
    "Cannot destructure property 'projects' of 'undefined' as it is undefined.\n" +
    '    at validateStaticDependency (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/project-graph/project-graph-builder.js:351:40)\n' +
    '    at validateDependency (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@16.10.0/node_modules/nx/src/project-graph/project-graph-builder.js:311:9)\n' +
    '    at Object.createDependencies (/Users/jbadeau/git/jose/node_modules/.pnpm/@jnxplus+nx-maven@0.12.0/node_modules/@jnxplus/nx-maven/src/graph/create-dependencies.js:28:45)\n' +
    '    at /Users/jbadeau/git/jose/node_modules/.pnpm/nx@17.0.0/node_modules/nx/src/project-graph/build-project-graph.js:180:47\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at updateProjectGraphWithPlugins (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@17.0.0/node_modules/nx/src/project-graph/build-project-graph.js:178:47)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async buildProjectGraphUsingContext (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@17.0.0/node_modules/nx/src/project-graph/build-project-graph.js:98:15)\n' +
    '    at async buildProjectGraphUsingProjectFileMap (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@17.0.0/node_modules/nx/src/project-graph/build-project-graph.js:62:24)\n' +
    '    at async createAndSerializeProjectGraph (/Users/jbadeau/git/jose/node_modules/.pnpm/nx@17.0.0/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:198:55)',
  message: 'Failed to process project dependencies with "@jnxplus/nx-maven".\n' +
    "Cannot destructure property 'projects' of 'undefined' as it is undefined.\n" +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}

```

**Comment by nosaku** [comment]
Same here. Just upgraded to Nx 17 and got this error when building a NestJS project.

**Comment by nosaku** [comment]
I tried adding console.log statements in the node_modules/nx/src but it is no appearing? Any idea?

**Comment by khalilou88** [comment]
@nosaku I already fixed this error in PR, will merge it today

**Comment by nosaku** [comment]
Thank you @khalilou88

**Comment by khalilou88** [comment]
@jbadeau  @nosaku  I added support of nx 17 in version 0.12.1 of nx-maven.

**Comment by nosaku** [comment]
> @jbadeau @nosaku I added support of nx 17 in version 0.12.1 of nx-maven.

Thanks you so much. I will give a try now.

**Comment by nosaku** [comment]
@khalilou88 Is 0.12.1 released? Getting error that package is not found.

**Comment by khalilou88** [comment]
@nosaku yes released and smoke tests are working fine, they have the same error before this release

**Comment by nosaku** [comment]
All good thanks a lot
