### ISSUE TITLE
nx-maven application generator fails

### ISSUE THREAD

**Issue by gitLinda** [khalilou88/jnxplus#555]
Hi

The nx-maven application generator throws an error (version 0.14.1):

````shell
The "request" argument must be of type string. Received an instance of Object

Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
If the error persists, please run "nx reset".
````

Steps to reproduce:
1. generate a new nx repo
````shell
linda@DESKTOP-BJCBISQ:~/tmp$ npx create-nx-workspace@16.10.0 foo

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · integrated
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.10.0 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: foo.
````
2. Add nx-maven dependency
````shell
linda@DESKTOP-BJCBISQ:~/tmp/foo$ npm install --save-dev @jnxplus/nx-maven
````
3. call the init generator
````shell
linda@DESKTOP-BJCBISQ:~/tmp/foo$ npx nx generate @jnxplus/nx-maven:init

>  NX  Generating @jnxplus/nx-maven:init

✔ Which version of Java would you like to use? · 17
✔ What groupId would you like to use? · com.example.foo
✔ What parentProjectName would you like to use? · root-parent-project
✔ What project version would you like to use? · 0.0.1-SNAPSHOT
✔ Where do you want Maven config and projects to be placed? · 
✔ How to handle dependency management? · spring-boot-parent-pom
CREATE .mvn/wrapper/maven-wrapper.jar
CREATE .mvn/wrapper/maven-wrapper.properties
CREATE mvnw
CREATE mvnw.cmd
CREATE pom.xml
UPDATE nx.json
UPDATE .gitignore
CREATE .prettierrc
CREATE .prettierignore
CREATE .gitattributes
````
4. Call the app generator
````shell
linda@DESKTOP-BJCBISQ:~/tmp/foo$ npx nx generate @jnxplus/nx-maven:application app1

 >  NX   The "request" argument must be of type string. Received an instance of Object

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
````
The error when I run with verbose:
````shell
 >  NX   The "request" argument must be of type string. Received an instance of Object

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

{
  stack: 'TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received an instance of Object\n' +
    '    at new NodeError (node:internal/errors:399:5)\n' +
    '    at validateString (node:internal/validators:163:11)\n' +
    '    at Function.resolve (node:internal/modules/cjs/helpers:115:5)\n' +
    '    at getPluginPathAndName (/home/linda/tmp/foo/node_modules/nx/src/utils/nx-plugin.js:32:30)\n' +
    '    at loadNxPluginAsync (/home/linda/tmp/foo/node_modules/nx/src/utils/nx-plugin.js:70:32)\n' +
    '    at loadNxPlugins (/home/linda/tmp/foo/node_modules/nx/src/utils/nx-plugin.js:124:27)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async retrieveProjectConfigurations (/home/linda/tmp/foo/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:56:21)\n' +
    '    at async processCollectedUpdatedAndDeletedFiles (/home/linda/tmp/foo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:129:34)\n' +
    '    at async processFilesAndCreateAndSerializeProjectGraph (/home/linda/tmp/foo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:165:17)',
  message: 'The "request" argument must be of type string. Received an instance of Object\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".',
  code: 'ERR_INVALID_ARG_TYPE'
}
````

**Comment by khalilou88** [comment]
nx maven 0.14.1 only work with nx 17. 
To use nx 16.10 you need to use  0.12.0 version  but you will not have mavenRootDirectory option

**Comment by gitLinda** [comment]
Thanks for the fast reply! Will try :)
