### ISSUE TITLE
Gradle :projectDependencyTask fails if NX Daemon is not running

### ISSUE THREAD

**Issue by paulhobbel** [khalilou88/jnxplus#955]
There seems to be an issue in the Gradle plugin where if the `.nx/cache` folder doesn't exist the `:projectDependencyTask` fails.
If I manually create the `.nx/cache` folder all is fine.

Way to test it:
1. Create new NX project `npx create-nx-workspace@latest`
2. Install the NX gradle plugin `npm install --save-dev @jnxplus/nx-gradle`
3. Add project `npx nx g @jnxplus/nx-gradle:app my-app`
4. Shut down the NX Daemon `npx nx reset` (This also removes the .nx/cache folder)
5. Run the build command `npx nx build my-app`

The following error will be thrown:
```
Unable to create nodes for nx.json using plugin @jnxplus/nx-gradle.

         Inner Error: Error: Command failed: ./gradlew :projectDependencyTask --outputFile=/home/ssm-user/actions-runner/obfuscated/.nx/cache/nx-gradle-deps.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectDependencyTask'.
> java.io.FileNotFoundException: /home/ssm-user/actions-runner/obfuscated/.nx/cache/nx-gradle-deps.json (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at exports.createNodes (/home/ssm-user/actions-runner/obfuscated/packages/nx-gradle/src/graph/create-nodes.ts:17:13)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/ssm-user/actions-runner/obfuscated/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:146:25)
    at createProjectConfigurations (/home/ssm-user/actions-runner/obfuscated/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
    at _retrieveProjectConfigurations (/home/ssm-user/actions-runner/obfuscated/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
    at retrieveProjectConfigurations (/home/ssm-user/actions-runner/obfuscated/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
    at buildProjectGraphAndSourceMapsWithoutDaemon (/home/ssm-user/actions-runner/obfuscated/node_modules/nx/src/project-graph/project-graph.js:73:69)

 NX   Unable to create nodes for nx.json using plugin @jnxplus/nx-gradle.


         Inner Error: Error: Command failed: ./gradlew :projectDependencyTask --outputFile=/home/ssm-user/actions-runner/obfuscated/.nx/cache/nx-gradle-deps.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projectDependencyTask'.
> java.io.FileNotFoundException: /home/ssm-user/actions-runner/obfuscated/.nx/cache/nx-gradle-deps.json (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
```

Currently as workaround I just create the `.nx/cache` folder with `mkdir -p .nx/cache` and then the error does not occur

**Comment by khalilou88** [comment]
@paulhobbel Please try version 0.42.1

**Comment by paulhobbel** [comment]
Nice that indeed fixes the issue, thanks for the quick fix!
